[2025-04-18T03:08:41.166+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.taxi_data_to_parquet manual__2025-04-18T03:04:18.591369+00:00 [queued]>
[2025-04-18T03:08:41.221+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.taxi_data_to_parquet manual__2025-04-18T03:04:18.591369+00:00 [queued]>
[2025-04-18T03:08:41.222+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-04-18T03:08:41.245+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): taxi_data_to_parquet> on 2025-04-18 03:04:18.591369+00:00
[2025-04-18T03:08:41.257+0000] {standard_task_runner.py:57} INFO - Started process 568 to run task
[2025-04-18T03:08:41.272+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'taxi_data_to_parquet', 'manual__2025-04-18T03:04:18.591369+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpv5vm2avn']
[2025-04-18T03:08:41.278+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask taxi_data_to_parquet
[2025-04-18T03:08:41.341+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-18T03:08:41.426+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.taxi_data_to_parquet manual__2025-04-18T03:04:18.591369+00:00 [running]> on host ccadf5826b20
[2025-04-18T03:08:41.641+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='taxi_data_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T03:04:18.591369+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T03:04:18.591369+00:00'
[2025-04-18T03:08:41.646+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-18T03:08:41.651+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/csv_to_parquet_duckdb.py']
[2025-04-18T03:08:41.758+0000] {subprocess.py:86} INFO - Output:
[2025-04-18T03:08:42.072+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-18T03:08:42.073+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/csv_to_parquet_duckdb.py", line 84, in <module>
[2025-04-18T03:08:42.075+0000] {subprocess.py:93} INFO -     convert_csv_to_parquet(
[2025-04-18T03:08:42.076+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/csv_to_parquet_duckdb.py", line 64, in convert_csv_to_parquet
[2025-04-18T03:08:42.077+0000] {subprocess.py:93} INFO -     raise FileNotFoundError(f"CSV file not found: {csv_path}")
[2025-04-18T03:08:42.078+0000] {subprocess.py:93} INFO - FileNotFoundError: CSV file not found: /Users/lbw1125/Desktop/de-project/***/data/customers.csv
[2025-04-18T03:08:42.093+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-18T03:08:42.152+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T03:08:42.174+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=data_ingestion, task_id=taxi_data_to_parquet, execution_date=20250418T030418, start_date=20250418T030841, end_date=20250418T030842
[2025-04-18T03:08:42.252+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task taxi_data_to_parquet (Bash command failed. The command returned a non-zero exit code 1.; 568)
[2025-04-18T03:08:42.289+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-18T03:08:42.313+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
