[2025-04-18T03:04:27.373+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.download_taxi_data manual__2025-04-18T03:04:18.591369+00:00 [queued]>
[2025-04-18T03:04:27.387+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.download_taxi_data manual__2025-04-18T03:04:18.591369+00:00 [queued]>
[2025-04-18T03:04:27.425+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-18T03:04:27.453+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): download_taxi_data> on 2025-04-18 03:04:18.591369+00:00
[2025-04-18T03:04:27.462+0000] {standard_task_runner.py:57} INFO - Started process 457 to run task
[2025-04-18T03:04:27.483+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'download_taxi_data', 'manual__2025-04-18T03:04:18.591369+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpxqaiorue']
[2025-04-18T03:04:27.543+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask download_taxi_data
[2025-04-18T03:04:27.593+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-18T03:04:27.765+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.download_taxi_data manual__2025-04-18T03:04:18.591369+00:00 [running]> on host ccadf5826b20
[2025-04-18T03:04:28.005+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='download_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T03:04:18.591369+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T03:04:18.591369+00:00'
[2025-04-18T03:04:28.008+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-18T03:04:28.010+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/scripts/download_data.sh ']
[2025-04-18T03:04:28.036+0000] {subprocess.py:86} INFO - Output:
[2025-04-18T03:04:28.049+0000] {subprocess.py:93} INFO - [2025-04-18 03:04:28] INFO: Script started, processing fashion retail stores dataset
[2025-04-18T03:04:28.058+0000] {subprocess.py:93} INFO - [2025-04-18 03:04:28] INFO: Downloading dataset from Kaggle...
[2025-04-18T03:05:57.496+0000] {subprocess.py:93} INFO - [2025-04-18 03:05:57] INFO: Extracting files to /opt/***/data/raw...
[2025-04-18T03:08:00.566+0000] {subprocess.py:93} INFO - [2025-04-18 03:08:00] INFO: Cleaning temporary files...
[2025-04-18T03:08:01.890+0000] {subprocess.py:93} INFO - [2025-04-18 03:08:01] INFO: Processing completed! Data files available at: /opt/***/data/raw
[2025-04-18T03:08:01.892+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-18T03:08:02.225+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=download_taxi_data, execution_date=20250418T030418, start_date=20250418T030427, end_date=20250418T030802
[2025-04-18T03:08:02.693+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-18T03:08:02.841+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
