[2025-04-18T16:37:25.863+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.local_data_to_gcs_task manual__2025-04-18T03:20:57.015355+00:00 [queued]>
[2025-04-18T16:37:25.941+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.local_data_to_gcs_task manual__2025-04-18T03:20:57.015355+00:00 [queued]>
[2025-04-18T16:37:25.942+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2025-04-18T16:37:25.964+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): local_data_to_gcs_task> on 2025-04-18 03:20:57.015355+00:00
[2025-04-18T16:37:25.976+0000] {standard_task_runner.py:57} INFO - Started process 3493 to run task
[2025-04-18T16:37:25.983+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'local_data_to_gcs_task', 'manual__2025-04-18T03:20:57.015355+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmptt704kz1']
[2025-04-18T16:37:26.023+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask local_data_to_gcs_task
[2025-04-18T16:37:26.070+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-18T16:37:26.156+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.local_data_to_gcs_task manual__2025-04-18T03:20:57.015355+00:00 [running]> on host 65b150f242e5
[2025-04-18T16:37:26.345+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='local_data_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T03:20:57.015355+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T03:20:57.015355+00:00'
[2025-04-18T16:37:27.272+0000] {data_ingestion.py:50} ERROR - Failed to upload /opt/***/data/parquet/customers.parquet to customers.parquet: 404 POST https://storage.googleapis.com/upload/storage/v1/b/fashion_sales-storage-bucket/o?uploadType=resumable: {
  "error": {
    "code": 404,
    "message": "The specified bucket does not exist.",
    "errors": [
      {
        "message": "The specified bucket does not exist.",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>)
[2025-04-18T16:37:27.522+0000] {data_ingestion.py:50} ERROR - Failed to upload /opt/***/data/parquet/products.parquet to products.parquet: 404 POST https://storage.googleapis.com/upload/storage/v1/b/fashion_sales-storage-bucket/o?uploadType=multipart: {
  "error": {
    "code": 404,
    "message": "The specified bucket does not exist.",
    "errors": [
      {
        "message": "The specified bucket does not exist.",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>)
[2025-04-18T16:37:27.894+0000] {data_ingestion.py:50} ERROR - Failed to upload /opt/***/data/parquet/transactions.parquet to transactions.parquet: 404 POST https://storage.googleapis.com/upload/storage/v1/b/fashion_sales-storage-bucket/o?uploadType=resumable: {
  "error": {
    "code": 404,
    "message": "The specified bucket does not exist.",
    "errors": [
      {
        "message": "The specified bucket does not exist.",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>)
[2025-04-18T16:37:27.897+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-18T16:37:27.919+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=local_data_to_gcs_task, execution_date=20250418T032057, start_date=20250418T163725, end_date=20250418T163727
[2025-04-18T16:37:28.080+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-18T16:37:28.118+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
